### ISSUE TITLE
openDrawerOffset increases right margin every open/close

### ISSUE THREAD

**Issue by cameronmoreau** [root-two/react-native-drawer#349]
A strange bug popped up after I updated from RN 0.49 to 0.55.2

### What's wrong
When setting `openDrawerOffset` to anything other than `0`, the content width becomes smaller than the container. This results in, every time the drawer is opened, the content width slowly shrinks. I added some screenshots as well.

I'm guessing it may be due to the rounding when calculating the offset? On iOS RCTView recently changed and [this issue may have something to do](https://github.com/facebook/react-native/issues/18638) with the error.

### What's expected
When the drawer is open, content should match the width of the drawer and its `openDrawerOffset`

Made the background a different color so you can tell easily.

First open, you can see that the content width doesn't match the drawer
<img src="https://user-images.githubusercontent.com/732722/38700214-f1c5cd20-3e5f-11e8-9c46-b2522bd96392.png" height="500" >

8th open, you can see it slowly shrinking
<img src="https://user-images.githubusercontent.com/732722/38700222-f76814ae-3e5f-11e8-8c1a-83deeb91f429.png" height="500" >

This is with `0` offset, no issues
<img src="https://user-images.githubusercontent.com/732722/38700517-edffa1d8-3e60-11e8-8b65-b8d0fd6b7fa3.png" height="500" >

### My versions
"react": "^16.3.1",
"react-native": "^0.55.2",
"react-native-drawer": "^2.5.0",

**Comment by bteng22** [comment]
My team has also updated RN from 0.54.0 to 0.55.2 and is experiencing the same issue. Previously, it was working fine on 0.54.0. 

We're using the same versions of the following packages as @cameronmoreau above:
"react": "^16.3.1",
"react-native": "^0.55.2",
"react-native-drawer": "^2.5.0",

This issue is only appearing on iOS, but it seems to work fine on Android devices. 

Any extra insight would be super appreciated!

**Comment by longvo10** [comment]
I had the same problem with "react-native": "0.55.2",

**Comment by nppull** [comment]
same bug, RN 0.55.2 , ios 🤕 🤕 🤕 🤕

**Comment by patrickleemsantos** [comment]
Same with me, it happened after upgrade to RN 0.55.2 and for IOS only.

**Comment by foyarash** [comment]
Temporary fix for me was to remove the parallax tween handler

**Comment by rk85097** [comment]
Any solution here?? this is making it not useable... :/

**Comment by mtiziano** [comment]
I've fixed that issue in this PR https://github.com/root-two/react-native-drawer/pull/352

**Comment by roycclu** [comment]
@numez the fix only works in development mode
I manually put in your two lines of "+	this._length = Math.round(tweenValue*2)/2;"
Worked on simulator.
When exported for distribution, error still occurs.

**Comment by mtiziano** [comment]
it works for me, @roycclu can you share **Your Environment** and **How to reproduce**?

**Comment by ryanmr** [comment]
I had this issue in my app after upgrading RN .54 -> .55. I can confirm the bug fix in your PR #352 fixes the issue for my app, at least in the iOS simulator.

As a temporary fix (modifying package source code is not an option for my development) I have temporarily switched iOS users to use the `static` drawer type option. I am looking forward to seeing your PR accepted soon though!

**Comment by JasonFehr** [comment]
Same problem.

I reverted to RN 0.54 to fix it, hope there's a bug fix soon!

**Comment by ItsNoHax** [comment]
@numez Your fix only works on normal iPhone models, the PLUS models or iPhone X still have the problem.

**Comment by roycclu** [comment]
Okay, thanks for clarifying.
The issue I saw earlier with the fix is not due to simulator vs device.

It was due to iPhone X. Issue still exists on iPhone X

**Comment by mtiziano** [comment]
Yes @roycclu 
Latest commit in https://github.com/root-two/react-native-drawer/pull/352 PR should be fine

**Comment by ItsNoHax** [comment]
@numez Man you are starting to piss me off. Please check your 'fix' before you tell others to use it. Still broken on iPhone PLUS models.

**Comment by simonepauro** [comment]
Thank you @numez working great on iPhone Plus and iPhone X!

**Comment by inspireui** [comment]
same issues

Thank @numez for fixing but the PR is not worked for me on iPhoneX

**Comment by mgvictor7** [comment]
Same issue with iPhone Plus models  and iPhone X using the PR #352 

"react": "^16.2.0",
"react-native": "^0.55.4",
"react-native-drawer": "^2.5.0",

**Comment by jhonmer-araujo** [comment]
@hoangvuanhdevelopervn how did you fix this issue?

**Comment by Dimon70007** [comment]
same bug on "iphone 6s Plus" with react-native@0.55.4 and [that fix](https://github.com/root-two/react-native-drawer/pull/352/files). I have seen the same bug when tried to change top/bottom/left/right styleProps through Animated.timing function in Animated.View and has fixed it when replace top/bottom/left/right with transform/translateX/translateY

**Comment by sdg9** [comment]
For what it's worth I did a git bisect between the react-native 0.54.x and 0.55.x and found that [this commit in React Native](https://github.com/facebook/react-native/commit/f91f7d91a1e937785438d568ff629d00307ca75a) is what causes the problem, at least when testing on iPhone X simulator.  I don't have a solution yet.

**Comment by nguyenvanphuc2203** [comment]
use type="static" resolve this issue
