### ISSUE TITLE
Help to block touches from child components

### ISSUE THREAD

**Issue by rgoldiez** [root-two/react-native-drawer#68]
Need help.... I'm trying to **block** child components from receiving touch/pan gestures while the drawer is open.  As it stands now, when my drawer is open, the user could touch/navigate in the small open section and even bring up the keyboard while the drawer stays open.  I'm trying to configure the drawer to capture those gestures and simply close the drawer and present the main view back to the user.  What am I doing wrong?

```
<Drawer
   ref='leftDrawer'
   content={<LeftDrawer />}
   type='static'
   side='left'
   openDrawerOffset={0.2}
   onOpen={this.openLeftDrawer}
   onOpenStart={dismissKeyboard}
   onPeak={() => {StatusBarIOS.setHidden(true, 'slide'); dismissKeyboard()}} <-- to be replaced w/ official prop
   onClose={this.closeDrawers}
   styles={{main: {shadowColor: '#000000', shadowOpacity: 0.4, shadowRadius: 3}}}
   tweenHandler={Drawer.tweenPresets.parallax}
   tweenDuration={150}
   negotiatePan={true}
   panOpenMask={5}
   captureGestures={true}
   panCloseMask={0.2}
   disabled={this.state.leftDrawerDisabled}
   >
   <View style={styles.container}>
   ...
   </View>
</Drawer>
```

**Comment by rt2zz** [comment]
This looks correct.. there could possibly be a conflict between captureGestures and negotiatePan.

One thing to try first though: set `tapToClose={true}`

**Comment by rgoldiez** [comment]
Just tried.  Same result.  

I think I helped w/ the negotiatePan... figures it would cause problems :smile:

**Comment by realjamie** [comment]
+1

**Comment by realjamie** [comment]
+1... I have a similar problem. My drawer code looks like below, and I have some touchable views on my drawer. The problem is that, if I set _captureGestures_ to true, it will block onPress handlers of touchable items too. But if I set _captureGestures_ to false, the touch events of children components are not disabled... Is there any thought about how to  solve this?

```
    <Drawer
        content={this._renderMenu()}
        onClose={this.props.onClose}
        onOpen={this.props.onOpen}
        openDrawerOffset={0.1}
        panCloseMask={1}
        panOpenMask={0}
        panStartCompensation
        ref="drawer"
        styles={stylesRaw.drawer}
        tapToClose
        type={'displacement'}
        tweenDuration={350}
        tweenHandler={this._handleTween}
        tweenEasing={'linear'}>
          {this.props.children}
      </Drawer>
```

**Comment by rt2zz** [comment]
@realjamie there is definitely a bug, I am going to take a look at this today and let you know what I find

**Comment by realjamie** [comment]
Thanks for quick response, @rt2zz !

**Comment by rt2zz** [comment]
@realjamie @rgoldiez ok this _might_ be fixed in v1.15.0. The way pan handlers work in react-native makes the combination of captureGestures and negotiatePan at odds with eachother. What I did to work around this is give captureGestures precedence when the drawer is open (which is probably 95% of the time the intuitive behavior).

Let me know how that goes :)

**Comment by realjamie** [comment]
@rt2zz , thanks for your quick fix and response!

With drawer (v1.16.6) type = "displace" and captureGestures = true, now I'm able to click the touchable items on the drawer and trigger the onPress handler. However, touch events of children components are not disabled. My Drawer are set as below. Is there any way I can disable the children components? Thanks!

```
  <Drawer
        captureGestures
        content={this._renderMenu()}
        onClose={this.props.onClose}
        onOpen={this.props.onOpen}
        openDrawerOffset={0.1}
        panCloseMask={1}
        panOpenMask={0}
        panStartCompensation
        ref="drawer"
        styles={stylesRaw.drawer}
        tapToClose
        type="displace"
        tweenDuration={350}
        tweenHandler={this._handleTween}
        tweenEasing={'linear'}>
          {this.props.children}
      </Drawer>
```

**Comment by MacKentoch** [comment]
@rt2zz having same issue I updated to v1.16.7. 

But no chance... It still occurs : I can tap children button when drawer is opened.

In pure iOS, side menu is less tricky, we just make some kind `screen shot`of the content when opening drawer so that there is no event possible when drawer is opened.

I would be nice if it were possible with react native but I don't think so.

``` javascript

      <Drawer
        ref="drawer"
        onOpen={()=>this.handlesDrawerOpen()}
        type="static"
        panCloseMask={0.2}

        tapToClose={true}
        negotiatePan={true}
        captureGestures={true} 

        openDrawerOffset={0.2}
        closedDrawerOffset={-3}
        content={DrawerContent}
      >
     // ...
    </Drawer>
```

**Comment by realjamie** [comment]
I tried to solve this issue in this PR: https://github.com/root-two/react-native-drawer/pull/103 Would like to ask for help to verify my solution. Thanks!

**Comment by rt2zz** [comment]
awesome! I will do my best to check this out this week.

**Comment by MacKentoch** [comment]
@rt2zz is this PR coming in next release?

I wait for this feature before submitting my application.

My request is not to say "hurry" (_omg, how would someone dare?_ :smile: ) but to know when I can plan to submit my application.

Thank you @realjamie for submitting a PR to solve this issue.

**Comment by rt2zz** [comment]
@MacKentoch understood. I just released a new version under the next tag (`npm i react-native-drawer@next` that includes this functionality. Capture gestures is now much more aggressive, and can be set to only capture when drawer is open `captureGestures='open'`.

TBH I would not yet consider this production ready, but neither was v1.16. If you don't mind taking the new version for a test drive, I think we can iron out any remaining bugs and get this production ready in the next few days. :+1:

**Comment by MacKentoch** [comment]
@rt2zz I updated to v2.0.0-alpha5.

**as a fast feedback :**
- It seems like an real improvement, when forcing `captureGestures='open'` 
- At this time, I encounter some little visual bugs but I have to dig into them before saying it comes from the drawer or my own code (_which I suspect_).

**more feedbacks coming soon.**

**Comment by MacKentoch** [comment]
Something's wrong when I manually close drawer with `this.refs.drawer.close();` (_I have to close it from my drawer content — a side menu for navigation like usual_).

I `console.logged` these drawer props  : 
- onOpen
- onCloseStart
- onClose

And results : 
- When drawer closes because of `tapToClose={true}` it is fine.
- When drawer closes because of a manual (`drawer.close()`) I see not 1 but 2 lines of `onClose` callbacks.

**Comment by 9mm** [comment]
I'm not sure if you guys are talking about the same issue, perhaps someone can fill me in. I'm trying to figure something out on iOS which is driving me crazy. I've tried every combination of drawer settings I can think of to no avail.

Basically 1 of 2 things happen
1. The drawer works properly, but when you tap to close, it actually triggers a click on the view which is slid off to the right. So in my case it's a bunch of images of albums you can click on. If you tap to close, the sidebar properly closes but simultaneously goes to a new route as if you had clicked it normally
2. You tap to close, and it does the exact same thing as point 1 above (it goes to a new route), except the sidebar doesnt close. So now you are able to use the app in a tiny 20% width strip to the right of an open sidebar

I'm using this version: 

`"react-native-drawer": "2.0.0-beta1",`

```
      <DrawerIOS
        disabled={!!this.props.modalValues.hasModals}
        ref="drawer"
        type="static"
        onOpen={() => this.setState({isDrawerOpened: true})}
        onClose={() => this.setState({isDrawerOpened: false})}
        onOpenStart={() => {
          this._hideKeyboard();
          this._setStatusBarHidden(true);
        }}
        onCloseStart={() => this._setStatusBarHidden(false)}
        content={sidebarContent}
        openDrawerOffset={0.2}
        captureGestures={this.state.isDrawerOpened}
        negotiatePan={!this.state.isDrawerOpened}
        tapToClose={true}
        styles={styles.ios}
        tweenDuration={110}
        tweenEasing="easeInOutCirc"
        side='left'>
        {content}
      </DrawerIOS>
```

**Comment by rt2zz** [comment]
@9mm I think you should try the new `captureGestures="open"` format which will only capture gestures while the drawer is open. 

Beyond that I have lost track a bit of all of the various issue embedded in this one. If behavior is still inconsistent or buggy in v2 feel free to open a new issue with the specifics.

**Comment by hector** [comment]
Hi, I know this is is marked as closed but could anyone write an example of how to achieve the described behaviour? I cannot get it working.
Thanks in advance.

**Comment by rgoldiez** [comment]
@hector - Can you share your Drawer setup/property?  The key property you want to set it `captureGestures='open'` (if you want to capture / block gestures when the drawer is open).  But if you can share what you're doing it will be easier to help.

**Comment by hector** [comment]
sure @rgoldiez 

```
<Drawer
                ref='navigation'
                open={this.props.navigationState.open}
                type='overlay'
                onOpen={this.onOpen}
                onClose={this.onClose}
                content={<ModesView name={this.props.navigationState.key}/>}
                openDrawerOffset={0.25}
                acceptPan
                captureGestures={false}
                negotiatePan={false}
                panOpenMask={0.0}
                panCloseMask={0.99}
                styles={ModesDrawer.styles}
                tweenHandler={this.tweenHandler}
                tweenEasing={'easeInOutQuad'}
            >
                <DefaultRenderer
                    navigationState={this.props.navigationState.children[0]}
                    onNavigate={this.props.onNavigate} />
            </Drawer>
```

I have tried settings `captureGestures` to `true` and `open`, this avoids the child components (in the background) to receive clicks but the buttons on the drawer also stop receiving clicks, which is even worse.

**Comment by rgoldiez** [comment]
@hector - Try setting your `panCloseMask={0.25}`, the same value you set for your `openDrawerOffset`.  You'll also want to do something like `captureGestures='open'` as well.

**Comment by hector** [comment]
Thanks @rgoldiez.
This is how I had it set up before, it is functional because you can click the drawer buttons but cannot click the background. The problem is that I wanted to close the drawer sliding from anywhere, the drawer included, not only from the 25% of the visible background. The truth is that I am trying to imitate the behaviour of Google's drawers.
I have the impression this behaviour cannot be accomplished currently.
